*** Settings ***
Documentation  Project global definitions.

*** Variables ***
${URL}           http://localhost:5173
${BROWSER}       firefox

${API_HOST}      http://127.0.0.1:5000
${API_USER}      bookstore_admin
${API_PASS}      admin123

${DB_NAME}       bookstoredb
${DB_USER}       root
${DB_PASS}       Coragem@123
${DB_HOST}       localhost
${DB_PORT}       3306

${KAFKA_SERVER}  127.0.0.1:9092
